### ISSUE TITLE
Peer to peer code review.

### ISSUE THREAD

**Issue by brahimdidi** [azy64/Portfolio#8]
## Changes required :recycle: 
Hi Ally, great job so far.
I would like to suggest some changes for you, I noticed that you do not have a js file and you use inline javascript in the HTML.
I think it would be better if you write your javascript in a separate file.

Thanks :grin:

**Comment by azy64** [comment]
Thanks, Brahim for your issue, it would be fine it was  something javascript code I did  however in that case, the code from
